# Generated by Django 4.1.1 on 2022-12-03 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='punch_type',
            field=models.IntegerField(choices=[(0, 'Entrada'), (1, 'Almoço'), (2, 'Retorno'), (3, 'Saída')]),
        ),
        migrations.AlterField(
            model_name='clock',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 21, 16, 31, 504079)),
        ),
        migrations.DeleteModel(
            name='PunchType',
        ),
    ]
